apiVersion: apps/v1
kind: Deployment
metadata:
  name: dice-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dice-app
  template:
    metadata:
      labels:
        app: dice-app
    spec:
      containers:
      - name: dice-app
        image: nginx:1.25
